// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func MovimientoForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"form-card\"><div class=\"titulo-creacion-movimiento\"><h2 id=\"titulo-crear-movimiento\">Crear Movimiento</h2></div><form action=\"/movimientos\" method=\"POST\" id=\"form-movimiento\"><div class=\"form-group\"><label for=\"monto_mov\">Monto:</label> <input type=\"number\" step=\"any\" name=\"monto\" id=\"monto_mov\" placeholder=\"Ej: 150.50\" class=\"form-input\" required></div><div class=\"form-group\"><label for=\"tipo_mov\">Tipo:</label> <select name=\"tipo\" id=\"tipo_mov\" required class=\"form-input\"><option value=\"\">Seleccionar...</option> <option value=\"G\">Gasto</option> <option value=\"I\">Ingreso</option></select></div><div class=\"form-group\"><label for=\"descripcion_mov\">Descripción:</label> <input type=\"text\" name=\"descripcion\" id=\"descripcion_mov\" placeholder=\"Ej: Compra supermercado\" class=\"form-input\"></div><div class=\"form-group\"><label for=\"fechaMovimiento\">Fecha de Movimiento:</label> <input type=\"date\" name=\"fechaMovimiento\" id=\"fechaMovimiento\" class=\"form-input\" required></div><div class=\"form-group\"><button type=\"submit\" class=\"boton-crear-movimiento\">Crear Movimiento</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
