// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Movimiento struct {
	IDMovimiento    int32          `json:"id_movimiento"`
	IDUsuario       int32          `json:"id_usuario"`
	Monto           float64        `json:"monto"`
	Tipo            string         `json:"tipo"`
	Descripcion     sql.NullString `json:"descripcion"`
	FechaMovimiento time.Time      `json:"fecha_movimiento"`
}

type Usuario struct {
	IDUsuario     int32        `json:"id_usuario"`
	Nombre        string       `json:"nombre"`
	Apellido      string       `json:"apellido"`
	Email         string       `json:"email"`
	Contraseña    string       `json:"contraseña"`
	FechaRegistro sql.NullTime `json:"fecha_registro"`
}
