// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO Session (session_token, id_usuario, username, expires)
VALUES ($1, $2, $3, $4)
RETURNING session_token, id_usuario, username, expires
`

type CreateSessionParams struct {
	SessionToken string         `json:"session_token"`
	IDUsuario    int32          `json:"id_usuario"`
	Username     sql.NullString `json:"username"`
	Expires      time.Time      `json:"expires"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.SessionToken,
		arg.IDUsuario,
		arg.Username,
		arg.Expires,
	)
	var i Session
	err := row.Scan(
		&i.SessionToken,
		&i.IDUsuario,
		&i.Username,
		&i.Expires,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM Session
WHERE session_token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionToken string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, sessionToken)
	return err
}

const getSession = `-- name: GetSession :one
SELECT session_token, id_usuario, username, expires
FROM Session
WHERE session_token = $1 AND expires > NOW()
`

func (q *Queries) GetSession(ctx context.Context, sessionToken string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, sessionToken)
	var i Session
	err := row.Scan(
		&i.SessionToken,
		&i.IDUsuario,
		&i.Username,
		&i.Expires,
	)
	return i, err
}
